In [21]:
import pandas as pd

In [22]:
df = pd.read_excel("Student Lifestyle Survey  (Responses).xlsx")

In [23]:
df.head()

,Timestamp,Which class are you in?,What is your gender?,How long have you been preparing for NEET?,Do you take any additional coaching outside this institute?,"On a typical weekday, how many hours do you study (self-study only, not coaching)?",Do you study on weekends?,Which subject do you find hardest?,How many mock tests do you attempt per month?,Do you review your mistakes after each mock test?,...,Do you use your phone within 30 minutes of sleeping?,How stressed do you feel about NEET preparation on most days?,How confident are you about clearing NEET this year?,Do you take any breaks or do physical activity during the day?,"Do you do any other extra activities?(hobbies like gym, sports, music, art, dance, writing)",How much time do u spend on those Activity?,How would you describe your current mental state during preparation?,What was your score (%) in the most recent mock test you attempted?,"Compared to 3 months ago, your mock test scores are:",What is your target NEET score?
0,2026-06-29 18:59:44.354,12th,Female,6-12 months,No,2-4 hrs,"Yes, but less",Phy,1-2,Sometimes,...,Yes,3,3,Occasionally,Yes,1-2hrs,Burn Out,70-85%,same,650-700
1,2026-06-30 20:38:55.875,11th,Female,Less than 6 months,No,2-4 hrs,"Yes, but less",math,0,Always,...,Yes,5,5,"Yes, regularlt",No,Less than 1 hr,Neutral,50-70%,Haven't tracked,700+
2,2026-06-30 23:08:39.768,12th,Female,6-12 months,Yes,4-6hrs,"Yes, but less",Phy,3-5,Always,...,No,4,4,"Yes, regularlt",Yes,1-2hrs,Anxious,70-85%,Improving,500-600
3,2026-07-01 10:25:28.020,12th,Female,1-2 years,Yes,2-4 hrs,"Yes, Same as weekedays",Phy,3-5,Sometimes,...,Yes,5,3,Occasionally,Yes,1-2hrs,Struggling,50-70%,declining,500-600
4,2026-07-01 23:23:04.295,12th,Female,1-2 years,No,4-6hrs,More than weekdays,Phy,3-5,Sometimes,...,Yes,4,2,Occasionally,Yes,Less than 1 hr,Burn Out,50-70%,same,600-650

In [24]:
clean_df = df.copy()

In [25]:
print("Rows:", clean_df.shape[0])
print("Columns:", clean_df.shape[1])

Rows: 44
Columns: 23

In [26]:
clean_df.isnull().sum()

Timestamp                                                                                       0
Which class are you in?                                                                         0
What is your gender?                                                                            0
How long have you been preparing for NEET?                                                      0
Do you take any additional coaching outside this institute?                                     0
On a typical weekday, how many hours do you study (self-study only, not coaching)?              0
Do you study on weekends?                                                                       0
Which subject do you find hardest?                                                              0
How many mock tests do you attempt per month?                                                   0
Do you review your mistakes after each mock test?                                               0
On average, how many hours do you sleep per night?\n                                            0
What time do you usually go to sleep?                                                           0
How many hours per day do you spend on your phone (non-study)?                                  0
Do you use your phone within 30 minutes of sleeping?                                            0
How stressed do you feel about NEET preparation on most days?                                   0
How confident are you about clearing NEET this year?                                            0
Do you take any breaks or do physical activity during the day?                                  0
Do you do any other extra activities?(hobbies like gym, sports, music, art,  dance, writing)    0
How much time do u spend on those Activity?                                                     0
How would you describe your current mental state during preparation?                            0
What was your score (%) in the most recent mock test you attempted?                             0
Compared to 3 months ago, your mock test scores are:                                            0
What is your target NEET score?                                                                 0
dtype: int64

In [27]:
clean_df.duplicated().sum()

np.int64(0)

In [28]:
clean_df = clean_df.drop(columns=["Timestamp"])

In [32]:
column_names = {

    "Which class are you in?": "class",

    "What is your gender?": "gender",

    "How long have you been preparing for NEET?": "neet_prep_duration",

    "Do you take any additional coaching outside this institute?": "additional_coaching",

    "On a typical weekday, how many hours do you study (self-study only, not coaching)?": "self_study_hours",

    "Do you study on weekends?": "weekend_study",

    "Which subject do you find hardest?": "hardest_subject",

    "How many mock tests do you attempt per month?": "mock_tests_per_month",

    "Do you review your mistakes after each mock test?": "mistake_review",

    "On average, how many hours do you sleep per night?\n": "sleep_hours",

    "What time do you usually go to sleep?": "sleep_time",

    "How many hours per day do you spend on your phone (non-study)?": "phone_hours",

    "Do you use your phone within 30 minutes of sleeping?": "phone_before_sleep",

    "How stressed do you feel about NEET preparation on most days?": "stress_level",

    "How confident are you about clearing NEET this year?": "confidence_level",

    "Do you take any breaks or do physical activity during the day?": "physical_activity",

    "Do you do any other extra activities?(hobbies like gym, sports, music, art,  dance, writing)": "extra_activities",

    "How much time do u spend on those Activity?": "activity_hours",

    "How would you describe your current mental state during preparation?": "mental_state",

    "What was your score (%) in the most recent mock test you attempted?": "mock_score_range",

    "Compared to 3 months ago, your mock test scores are:": "score_trend",

    "What is your target NEET score?": "target_score_range"
}

clean_df = clean_df.rename(columns=column_names)

print(clean_df.columns.tolist())

['class', 'gender', 'neet_prep_duration', 'additional_coaching', 'self_study_hours', 'weekend_study', 'hardest_subject', 'mock_tests_per_month', 'mistake_review', 'sleep_hours', 'sleep_time', 'phone_hours', 'phone_before_sleep', 'stress_level', 'confidence_level', 'physical_activity', 'extra_activities', 'activity_hours', 'mental_state', 'mock_score_range', 'score_trend', 'target_score_range']

In [33]:
clean_df["hardest_subject"].value_counts()

hardest_subject
Phy     24
chem    14
math     3
bio      3
Name: count, dtype: int64

In [34]:
clean_df["hardest_subject"] = (
    clean_df["hardest_subject"]
    .str.strip()
    .str.lower()
    .replace({
        "phy": "Physics",
        "physics": "Physics",
        "chem": "Chemistry",
        "chemistry": "Chemistry",
        "math": "Mathematics",
        "mathematics": "Mathematics",
        "bio": "Biology",
        "biology": "Biology"
    })
)

In [35]:
clean_df["hardest_subject"].value_counts()

hardest_subject
Physics        24
Chemistry      14
Mathematics     3
Biology         3
Name: count, dtype: int64

In [36]:
clean_df["physical_activity"].value_counts()

physical_activity
Occasionally      19
Yes, regularlt    14
rarely            10
Never              1
Name: count, dtype: int64

In [37]:
clean_df["physical_activity"] = (
    clean_df["physical_activity"]
    .str.strip()
    .replace({
        "Yes, regularlt": "Yes, regularly",
        "regularlt": "Yes, regularly",
        "rarely": "Rarely",
        "occasionally": "Occasionally"
    })
)

In [38]:
clean_df["physical_activity"].value_counts()

physical_activity
Occasionally      19
Yes, regularly    14
Rarely            10
Never              1
Name: count, dtype: int64

In [39]:
clean_df["weekend_study"] = (
    clean_df["weekend_study"]
    .str.strip()
    .replace({
        "Yes, Same as weekedays": "Yes, same as weekdays"
    })
)

In [40]:
clean_df["score_trend"] = (
    clean_df["score_trend"]
    .str.strip()
    .str.capitalize()
)

In [41]:
clean_df["self_study_hours"].value_counts()

self_study_hours
2-4 hrs            22
4-6hrs             10
Less than 2hrs      9
More than 6 hrs     3
Name: count, dtype: int64

In [42]:
study_hours_map = {
    "Less than 2hrs": 1,
    "2-4 hrs": 3,
    "4-6hrs": 5,
    "More than 6 hrs": 7
}

clean_df["self_study_hours_mid"] = (
    clean_df["self_study_hours"]
    .map(study_hours_map)
)

In [43]:
sleep_hours_map = {
    "Less than 5hrs": 4,
    "5-6hrs": 5.5,
    "6-7hrs": 6.5,
    "7-8hrs": 7.5,
    "More than 8hrs": 9
}

clean_df["avg_sleep_hours"] = (
    clean_df["sleep_hours"]
    .map(sleep_hours_map)
)

In [44]:
phone_hours_map = {
    "Less than 1hr": 0.5,
    "1-2hrs": 1.5,
    "2-4hrs": 3,
    "More than 4hrs": 5
}

clean_df["avg_phone_hours"] = (
    clean_df["phone_hours"]
    .map(phone_hours_map)
)

In [45]:
activity_hours_map = {
    "Less than 1 hr": 0.5,
    "1-2hrs": 1.5,
    "More than 2hrs": 3
}

clean_df["avg_activity_hours"] = (
    clean_df["activity_hours"]
    .map(activity_hours_map)
)

In [46]:
mock_score_map = {
    "Below 30%": 20,
    "30-50%": 40,
    "50-70%": 60,
    "70-85%": 77.5,
    "Above 85%": 90
}

clean_df["mock_score_mid"] = (
    clean_df["mock_score_range"]
    .map(mock_score_map)
)

In [47]:
target_score_map = {
    "500-600": 550,
    "600-650": 625,
    "650-700": 675,
    "700+": 725
}

clean_df["target_score_mid"] = (
    clean_df["target_score_range"]
    .map(target_score_map)
)

In [48]:
clean_df.head()

,class,gender,neet_prep_duration,additional_coaching,self_study_hours,weekend_study,hardest_subject,mock_tests_per_month,mistake_review,sleep_hours,...,mental_state,mock_score_range,score_trend,target_score_range,self_study_hours_mid,avg_sleep_hours,avg_phone_hours,avg_activity_hours,mock_score_mid,target_score_mid
0,12th,Female,6-12 months,No,2-4 hrs,"Yes, but less",Physics,1-2,Sometimes,7-8hrs,...,Burn Out,70-85%,Same,650-700,3,7.5,3.0,1.5,77.5,675
1,11th,Female,Less than 6 months,No,2-4 hrs,"Yes, but less",Mathematics,0,Always,7-8hrs,...,Neutral,50-70%,Haven't tracked,700+,3,7.5,1.5,0.5,60.0,725
2,12th,Female,6-12 months,Yes,4-6hrs,"Yes, but less",Physics,3-5,Always,5-6hrs,...,Anxious,70-85%,Improving,500-600,5,5.5,0.5,1.5,77.5,550
3,12th,Female,1-2 years,Yes,2-4 hrs,"Yes, same as weekdays",Physics,3-5,Sometimes,6-7hrs,...,Struggling,50-70%,Declining,500-600,3,6.5,3.0,1.5,60.0,550
4,12th,Female,1-2 years,No,4-6hrs,More than weekdays,Physics,3-5,Sometimes,5-6hrs,...,Burn Out,50-70%,Same,600-650,5,5.5,1.5,0.5,60.0,625

In [49]:
clean_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 44 entries, 0 to 43
Data columns (total 28 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   class                 44 non-null     object
 1   gender                44 non-null     object
 2   neet_prep_duration    44 non-null     object
 3   additional_coaching   44 non-null     object
 4   self_study_hours      44 non-null     object
 5   weekend_study         44 non-null     object
 6   hardest_subject       44 non-null     object
 7   mock_tests_per_month  44 non-null     object
 8   mistake_review        44 non-null     object
 9   sleep_hours           44 non-null     object
 10  sleep_time            44 non-null     object
 11  phone_hours           44 non-null     object
 12  phone_before_sleep    44 non-null     object
 13  stress_level          44 non-null     int64
 14  confidence_level      44 non-null     int64
 15  physical_activity     44 non-null     object
 16  extra_activities      44 non-null     object
 17  activity_hours        44 non-null     object
 18  mental_state          44 non-null     object
 19  mock_score_range      44 non-null     object
 20  score_trend           44 non-null     object
 21  target_score_range    44 non-null     object
 22  self_study_hours_mid  44 non-null     int64
 23  avg_sleep_hours       44 non-null     float64
 24  avg_phone_hours       44 non-null     float64
 25  avg_activity_hours    44 non-null     float64
 26  mock_score_mid        44 non-null     float64
 27  target_score_mid      44 non-null     int64
dtypes: float64(4), int64(4), object(20)
memory usage: 9.8+ KB

In [50]:
clean_df.isnull().sum()

class                   0
gender                  0
neet_prep_duration      0
additional_coaching     0
self_study_hours        0
weekend_study           0
hardest_subject         0
mock_tests_per_month    0
mistake_review          0
sleep_hours             0
sleep_time              0
phone_hours             0
phone_before_sleep      0
stress_level            0
confidence_level        0
physical_activity       0
extra_activities        0
activity_hours          0
mental_state            0
mock_score_range        0
score_trend             0
target_score_range      0
self_study_hours_mid    0
avg_sleep_hours         0
avg_phone_hours         0
avg_activity_hours      0
mock_score_mid          0
target_score_mid        0
dtype: int64

In [51]:
clean_df[
    [
        "self_study_hours_mid",
        "avg_sleep_hours",
        "avg_phone_hours",
        "avg_activity_hours",
        "mock_score_mid",
        "target_score_mid"
    ]
].describe()

,self_study_hours_mid,avg_sleep_hours,avg_phone_hours,avg_activity_hours,mock_score_mid,target_score_mid
count,44.000000,44.000000,44.000000,44.000000,44.000000,44.000000
mean,3.318182,6.272727,2.272727,1.090909,68.693182,655.113636
std,1.667371,1.075383,1.250370,0.649443,17.780057,56.439808
min,1.000000,4.000000,0.500000,0.500000,20.000000,550.000000
25%,3.000000,5.500000,1.500000,0.500000,60.000000,625.000000
50%,3.000000,6.500000,1.500000,1.500000,77.500000,675.000000
75%,5.000000,7.500000,3.000000,1.500000,77.500000,675.000000
max,7.000000,9.000000,5.000000,3.000000,90.000000,725.000000

In [53]:
print(clean_df["hardest_subject"].value_counts())
print(clean_df["physical_activity"].value_counts())
print(clean_df["weekend_study"].value_counts())
print(clean_df["score_trend"].value_counts())

hardest_subject
Physics        24
Chemistry      14
Mathematics     3
Biology         3
Name: count, dtype: int64
physical_activity
Occasionally      19
Yes, regularly    14
Rarely            10
Never              1
Name: count, dtype: int64
weekend_study
Yes, but less            19
More than weekdays       19
Yes, same as weekdays     4
No                        2
Name: count, dtype: int64
score_trend
Improving          17
Same               11
Haven't tracked     8
Declining           8
Name: count, dtype: int64

In [54]:
clean_df.to_csv("student_lifestyle_cleaned.csv", index=False)

In [56]:
clean_df.head()

,class,gender,neet_prep_duration,additional_coaching,self_study_hours,weekend_study,hardest_subject,mock_tests_per_month,mistake_review,sleep_hours,...,mental_state,mock_score_range,score_trend,target_score_range,self_study_hours_mid,avg_sleep_hours,avg_phone_hours,avg_activity_hours,mock_score_mid,target_score_mid
0,12th,Female,6-12 months,No,2-4 hrs,"Yes, but less",Physics,1-2,Sometimes,7-8hrs,...,Burn Out,70-85%,Same,650-700,3,7.5,3.0,1.5,77.5,675
1,11th,Female,Less than 6 months,No,2-4 hrs,"Yes, but less",Mathematics,0,Always,7-8hrs,...,Neutral,50-70%,Haven't tracked,700+,3,7.5,1.5,0.5,60.0,725
2,12th,Female,6-12 months,Yes,4-6hrs,"Yes, but less",Physics,3-5,Always,5-6hrs,...,Anxious,70-85%,Improving,500-600,5,5.5,0.5,1.5,77.5,550
3,12th,Female,1-2 years,Yes,2-4 hrs,"Yes, same as weekdays",Physics,3-5,Sometimes,6-7hrs,...,Struggling,50-70%,Declining,500-600,3,6.5,3.0,1.5,60.0,550
4,12th,Female,1-2 years,No,4-6hrs,More than weekdays,Physics,3-5,Sometimes,5-6hrs,...,Burn Out,50-70%,Same,600-650,5,5.5,1.5,0.5,60.0,625

In [57]:
import os
os.getcwd()

'C:\\Users\\janhv\\Student Lifestyle Analysis'

In [58]:
os.listdir()

['.ipynb_checkpoints',
 '.student_lifestyle_analysis.ipynb.layout',
 'Student Lifestyle Survey  (Responses).xlsx',
 'student_lifestyle_analysis.ipynb',
 'student_lifestyle_cleaned.csv']